# Generated by Django 5.0.6 on 2024-05-15 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='donationname',
            new_name='donationame',
        ),
    ]
