# Generated by Django 5.0.6 on 2024-05-18 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_donationname_donation_donationame'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='collection_loc',
            new_name='collectionloc',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='donation_pic',
            new_name='donationpic',
        ),
        migrations.AddField(
            model_name='donation',
            name='donationarea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.donationarea'),
        ),
    ]
