# Generated by Django 5.0.6 on 2024-05-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_collection_loc_donation_collectionloc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donationpic',
            field=models.ImageField(blank=True, null=True, upload_to='donations/'),
        ),
    ]
