# Generated by Django 5.0.6 on 2024-05-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_donation_donationpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donationame',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
