# Generated by Django 5.0.6 on 2024-05-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_donation_donationame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donationpic',
            field=models.ImageField(null=True, upload_to='donation'),
        ),
    ]
